### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by didier-durand**
Hi there,
See below
Best,
Didier

**Motivation**
Improve documentation quality

**Changes**
Fixing a few typos and harmonizing the use of verbs for command description (no 's' seems to be the favorite of the project)

### CODE REVIEW

**Comment by didier-durand** [comment]
CLA has signed and sent according to https://github.com/hivemq/hivemq-community/blob/master/CONTRIBUTING.adoc#contributor-license-agreement

**Comment by MagiErber** [comment]
Hi @didier-durand,
thank you for your contribution. We received your signed CLA and will check your PR soon.

@cla-bot check

**Comment by didier-durand** [comment]
@MagiErber : thanks for your rapid feedback! Didier

**Comment by gitseti** [comment]
Hi @didier-durand , 

thanks for your help!
Some of your suggested documentation updates need to be reflected in the `help` command accordingly.
Therefore, I will create another PR for the CLI's help command soon.

Until then feel free to add any more suggestions about the documentation, also as a comment.

**Comment by didier-durand** [comment]
@gitseti : you're welcome!

**Review by gitseti — APPROVED** [review]

**Pull request closed without merging**
