### PR TITLE
fix a bug:

### PR DESCRIPTION
**Pull request by xiefeifeihu**
**Motivation**

When config auth.server.cafile in config.properties,Command Line doesn't take effect.It also need to add --cafile in command line.

Now I fix the bug.We Can specify the CA certificate both in config.properties and command line.

**Changes**
add line 83 in DefaultCLIProperties.java----put(SERVER_CERTIFICATE, null);
add line 142 to 144 in AbstractCommonFlags.java----initialize certificates collection

### CODE REVIEW

**Comment by schaebo** [comment]
@cla-bot check

**Comment by gitseti** [comment]
Thanks for the contribution, @xiefeifeihu! 

Please sign the Contributor License Agreement (https://www.hivemq.com/downloads/Contributor_License_Agreement.pdf) and send it to contributing@hivemq.com so we can merge your requested changes.

**Comment by xiefeifeihu** [comment]
> Thanks for the contribution, @xiefeifeihu!
> 
> Please sign the Contributor License Agreement (https://www.hivemq.com/downloads/Contributor_License_Agreement.pdf) and send it to [contributing@hivemq.com](mailto:contributing@hivemq.com) so we can merge your requested changes.

I have already sent the pdf on January 8th.I send again a few minute ago.Please check your email.

**Comment by gitseti** [comment]
@cla-bot check

**Pull request merged**
